/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cisco_jabber_system_prt_LogCollecter */

#ifndef _Included_com_cisco_jabber_system_prt_LogCollecter
#define _Included_com_cisco_jabber_system_prt_LogCollecter
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_cisco_jabber_system_prt_LogCollecter_setupLogEnv
  (JNIEnv *, jobject);

void upLoadNativeLog(const char* log);

#ifdef __cplusplus
}
#endif
#endif
